DATABASE_HOST:
DATABASE_USERNAME:
DATABASE_PASSWORD:
DATABASE_NAME:

SECRET_KEY_BASE:

SERVER_HOST:

GOOGLE_API_KEY:
GOOGLE_APPLICATION_CREDENTIALS:

REDIS_URL:

# Sendgrid
SENDGRID_API_ID:
SENDGRID_API_KEY:

SMTP_ADDRESS:
SMTP_PORT:
SMTP_DOMAIN:
SMTP_USER_NAME:

DEFAULT_EMAIL_FROM:
DEFAULT_REPLY_TO:

DEFAULT_TEMPLATE_ID:

#Kafka
KAFKA_BROKERS:
KAFKA_CLIENT_ID:

#CSV
FILE_PATH:

#Sentry
SENTRY_DSN:
